# NumPy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object

* sophisticated (broadcasting) functions

* tools for integrating C/C++ and Fortran code

* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Numpy provides:
    1. Extension package to Python for multi-dimensional arrays
    2. Closer to hardware (Efficiency)
    3. Designed for scientific computation (convenience)
    4. Also known as array oriented Computing

In [2]:
import numpy as np

a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


__Why is it useful?__ Memory-efficient container that provides fast numerical operations.

In [3]:
# python lists
l = range(1000000)
%timeit [i**2 for i in l]

310 ms ± 2.93 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
a = np.arange(1000000)
%timeit a**2

2.83 ms ± 95.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# 1. Creating Arrays

In [5]:
a = np.array([1, 2, 3, 4])
twod = np.array([[0, 1, 1], [3, 4, 5]])
a

array([1, 2, 3, 4])

In [6]:
print(a.ndim)
print(twod.ndim)

1
2


In [7]:
a.shape

(4,)

# Using function


In [8]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b = np.arange(1, 100, 2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [10]:
# using linspace
a = np.linspace(0, 10, 6) # start, end, and number of points
a

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [11]:
# common arrays
a = np.ones([3,3])
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
a = np.zeros((3,3))
print(a)
a.ndim

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2

In [14]:
c = np.eye(3) # return a 2-D array with ones on the diagonal and zeros elsewhere
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
a = np.diag([1, 2, 3, 4]) # construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [16]:
# Create array using random

# create an array of given shape and populate it with random samples
a = np.random.rand(4)
a

array([0.17807648, 0.23443317, 0.53993647, 0.7151901 ])

In [17]:
a = np.random.randn(4) # return a sample from standard normal distribution
a

array([ 0.18724552, -1.56576321,  0.08185161,  1.3807412 ])

# 2. Basic Data Types

In [18]:
a = np.arange(10)
a.dtype

dtype('int64')

In [19]:
# explicityly specify which data-type:
a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
# the default data type is float for zeros and ones function

a = np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
a = np.array([True, False, True, False]) # Boolean Datatype
a.dtype

dtype('bool')

In [22]:
s = np.array(['Ram', 'Robert', 'Rahim'])

s.dtype

dtype('<U6')

# 3. Index and Slice

In [23]:
a = np.arange(10)
print(a[5])

5


In [24]:
# for multi dimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])
print(a[2,2])

3


In [25]:
a[2,1] = 5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

### Slicing

In [26]:
a = np.arange(10)

a[5:]

array([5, 6, 7, 8, 9])

In [27]:
a[1:9:2] # [start:end(exclusive):step]

array([1, 3, 5, 7])

In [29]:
# combining assignment and slicing:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [30]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# Copies and Views

 A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use. __np.may_share_memory()__ to check if two arrays share the same memory block
 
__when modifying the view, the original array is modified as well:__

In [31]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [33]:
np.shares_memory(a, b)

True

In [34]:
b[0] = 10

In [35]:
b

array([10,  2,  4,  6,  8])

In [36]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

# observation

Eventhough we modified b, it updated 'a' because both shared same memory.

In [38]:
a = np.arange(10)
c = a[::2].copy() # force a copy
c

array([0, 2, 4, 6, 8])

In [39]:
np.shares_memory(a,c)

False

In [40]:
c[0] = 10
c

array([10,  2,  4,  6,  8])

In [41]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Fancy Indexing

Numpy arrays can be indexed with slices, but also with bollean or integer arrays __(masks)__. This method is called __fancy indexing.__ It creates copies not views.

__Using Boolean Mask__

In [43]:
a = np.random.randint(0, 20, 15)
a

array([16, 16,  4,  2,  0,  8,  5, 15,  6, 17,  0, 17, 10,  5,  3])

In [46]:
mask = (a % 2 == 0)
mask
# Here mask is a numpy array that consists of boolean value for each element in 
# 'a' where true is for the even number and false for odd

array([ True,  True,  True,  True,  True,  True, False, False,  True,
       False,  True, False,  True, False, False])

In [47]:
extract_from_a = a[mask] # returns only the true values i.e only even numbers
extract_from_a

array([16, 16,  4,  2,  0,  8,  6,  0, 10])

__Indexing with a mask can be very useful to assign a new value to a sub-array:__

In [50]:
a[mask] = -1 # all the numbers which is even is converted to -1
a

array([-1, -1, -1, -1, -1, -1,  5, 15, -1, 17, -1, 17, -1,  5,  3])

__Indexing with an array of Integers__

In [51]:
a = np.arange(0, 100, 10)

In [53]:
# indexing can be done with an array of integers,
# where the same index can also be repeated
a[[2, 3, 4, 2, 3, 2]]

array([20, 30, 40, 20, 30, 20])

In [54]:
# New values can be assigned
a[[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])