In [3]:
import numpy as np

# Element-wise Operations

## 1. Basic Operations

__with scalars__

In [2]:
a = np.array([1, 2, 3, 4]) # create an array
a + 1

array([2, 3, 4, 5])

In [3]:
a ** 2

array([ 1,  4,  9, 16])

__All arithmetic operates elementwise__

In [10]:
b = np.ones([4]) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [11]:
a * b

array([2., 4., 6., 8.])

In [15]:
# matrix multiplication

c = np.diag([1, 2, 3, 4])
print("Method 1: \n")
print(c * c)
print("****************")
print("Method 2: \n")
print(c.dot(c))

Method 1: 

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
****************
Method 2: 

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 3, 4])
print(a == b)
print(a < b)

[False  True  True  True]
[ True False False False]


__Logical Operations__

In [18]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

print(np.logical_or(a, b))
print(np.logical_and(a, b))
print(a | b)

[ True  True  True False]
[ True False False False]
[ True  True  True False]


__Transcendental functions__

In [23]:
a = np.arange(1 ,4)
print(f"Sine  of a is: {np.sin(a)}")

Sine  of a is: [0.84147098 0.90929743 0.14112001]


In [24]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [25]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

# Basic Reductions


In [29]:
x = np.arange(1, 5)
np.sum(x)

10

In [38]:
# sum of rows and by columns
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [39]:
x.sum(axis=0) # column wise sum

array([4, 6])

In [41]:
x.sum(axis=1) # row wise sum

array([3, 7])

__Other Reductions__

In [42]:
x = np.array([1, 2, 3])
x.min()

1

In [44]:
x.argmin() # returns the index of minimum number in an array

0

In [45]:
x.argmax()

2

__Logical Operations__

In [46]:
np.all([True, False, True]) # logical AND

False

In [47]:
np.any([True, False]) # logical OR

True

In [9]:
# Note: can be used for array comparisons
a = np.zeros((50, 50))
np.any (a != 0)   # Is there any element of z != 0?

False

In [10]:
np.all(a == a)

True

In [14]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <=c)).all()

True

__Statistics__

In [15]:
x =np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [16]:
np.median(x)

1.5

In [17]:
np.median(y, axis=-1) # which means last axis

array([2., 5.])

In [19]:
x.std() # full population standard deviation

0.82915619758885

__Example__:

Data in populations.txt describes the populations of hares and lynxes (and carrots) in northen Canada During 2-yrs.

In [20]:
# load data into numpy array object
data = np.loadtxt('populations.txt')
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [23]:
year, hares, lynxes, carrots = data.T

In [22]:
year

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [24]:
# The mean population over time
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [25]:
# sample standard Deviations
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [26]:
# Which species has the highest population each year?
np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

# Broadcasting

Basic operations on numpy arrays (addition, etc.) are elementwise.

This works on arrays of the same size. Nevertheless, its also possible to do operations on arrays of different sizes if NumPy can transform these arrays so that they all have the same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:
<img src="broadcasting.png" />

In [31]:
a = np.tile(np.arange(0, 40, 10), (3, 1))
print(a)

a = a.T
print("Transpose of matrix a is: \n", a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
Transpose of matrix a is: 
 [[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [32]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [33]:
a + b 

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [38]:
a = np.arange(0, 40, 10)
a.shape
a

array([ 0, 10, 20, 30])

In [35]:
a = a[:, np.newaxis] # adds a new axis -> 2D array
a.shape

(4, 1)

In [36]:
a

array([[ 0],
       [10],
       [20],
       [30]])