# NumPy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object

* sophisticated (broadcasting) functions

* tools for integrating C/C++ and Fortran code

* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Numpy provides:
    1. Extension package to Python for multi-dimensional arrays
    2. Closer to hardware (Efficiency)
    3. Designed for scientific computation (convenience)
    4. Also known as array oriented Computing

In [3]:
import numpy as np

a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


__Why is it useful?__ Memory-efficient container that provides fast numerical operations.

In [4]:
# python lists
l = range(1000000)
%timeit [i**2 for i in l]

299 ms ± 15.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
a = np.arange(1000000)
%timeit a**2

2.81 ms ± 203 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# 1. Creating Arrays

In [9]:
a = np.array([1, 2, 3, 4])
twod = np.array([[0, 1, 1], [3, 4, 5]])
a

array([1, 2, 3, 4])

In [11]:
print(a.ndim)
print(twod.ndim)

1
2


In [8]:
a.shape

(4,)

# Using function


In [13]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b = np.arange(1, 100, 2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [22]:
# using linspace
a = np.linspace(0, 10, 6) # start, end, and number of points
a

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [24]:
# common arrays
a = np.ones([3,3])
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
a = np.zeros((3,3))
print(a)
a.ndim

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2