In [1]:
import numpy as np

# Element-wise Operations

## 1. Basic Operations

__with scalars__

In [2]:
a = np.array([1, 2, 3, 4]) # create an array
a + 1

array([2, 3, 4, 5])

In [3]:
a ** 2

array([ 1,  4,  9, 16])

__All arithmetic operates elementwise__

In [10]:
b = np.ones([4]) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [11]:
a * b

array([2., 4., 6., 8.])

In [15]:
# matrix multiplication

c = np.diag([1, 2, 3, 4])
print("Method 1: \n")
print(c * c)
print("****************")
print("Method 2: \n")
print(c.dot(c))

Method 1: 

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
****************
Method 2: 

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 3, 4])
print(a == b)
print(a < b)

[False  True  True  True]
[ True False False False]


__Logical Operations__

In [18]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

print(np.logical_or(a, b))
print(np.logical_and(a, b))
print(a | b)

[ True  True  True False]
[ True False False False]
[ True  True  True False]


__Transcendental functions__

In [23]:
a = np.arange(1 ,4)
print(f"Sine  of a is: {np.sin(a)}")

Sine  of a is: [0.84147098 0.90929743 0.14112001]


In [24]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [25]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

# Basic Reductions


In [29]:
x = np.arange(1, 5)
np.sum(x)

10

In [38]:
# sum of rows and by columns
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [39]:
x.sum(axis=0) # column wise sum

array([4, 6])

In [41]:
x.sum(axis=1) # row wise sum

array([3, 7])

__Other Reductions__

In [42]:
x = np.array([1, 2, 3])
x.min()

1

In [44]:
x.argmin() # returns the index of minimum number in an array

0

In [45]:
x.argmax()

2